### ISSUE TITLE
[Enhancement][Wishlist] Export interactive datalets

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#100]
Since datalets are already interactive visualisations of datasets in SPOD, would it be possible to export them (by sharing on other social media platforms or embedding into blogposts, for example) as a way to draw audiences to ROUTETOPA tools, SPOD specifically?

**Comment by lucavicidomini** [comment]
Hi all, the wordpress plugin is here: https://github.com/routetopa/wordpress-datalet

The 0.1 version was very quick and dirty, the 1.0 is a little bit quick and a little bit dirty... I am planning a new, more robust, version before the end of the month. 

The plugin is _not_ available on the Wordpress Plugin Directory because we need to rewrite the datalets code to respect their policy. This item has low priority right now.
