### ISSUE TITLE
when showing the list of dataset cocreated link to download document is wrong..

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#136]
.. since it opens the document in the same frame and not in a separated new frame.

**Comment by andrpet** [comment]
We can't reproduce the issue, the functionality seems to work correctly in all the supported browser. Can you share more info (spod platform, browser, os). Maybe your browser is set to open csv instead of downloading it.

**Comment by vitsca** [comment]
It did not work.. now it downloads an HTML file (Chrome on Mac OS X) but now another thing does not work (the link.. well.. separate issue!)

**Comment by andrpet** [comment]
Now we use FileSaver.js library to increase browser cross compatibility (the library use Blobs), the issue is solved for Chrome on Mac OS X. On Safari 6.1+ Blobs may be opened instead of saved sometimes—you may have to direct your Safari users to manually press <kbd>⌘</kbd>+<kbd>S</kbd> to save the file after it is opened. Using the `application/octet-stream` MIME type to force downloads [can cause issues in Safari](https://github.com/eligrey/FileSaver.js/issues/12#issuecomment-47247096)
