### ISSUE TITLE
Wrong Preview of media slider (for facebook)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#335]
When using the media slider, the preview of the first image is distorted because it is forced to be rectangular, also if the first image is square.. see image attached and the original datalet in http://spod.routetopa.eu/datalet/77
<img width="513" alt="schermata 2017-11-25 alle 10 48 50" src="https://user-images.githubusercontent.com/2544302/33229405-69065b74-d1ce-11e7-8a78-c53316258b04.png">

**Comment by andrpet** [comment]
The media slider has an unexpected behaviuor with webshot. Our hypothesis is that webshot does not interprete correctly the css property `object-fit: contain;`
Media slider is based on Camera project (https://www.pixedelic.com/plugins/camera/) ... maybe we have to chose another project in order to overcome this bug (it's a time expensive operation due to back compatibility and re-implementation)

**Comment by andrpet** [comment]
Maybe @rended can add some observations to the discussion

**Comment by rended** [comment]
Fixed
