### ISSUE TITLE
Push e-mails notification

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#34]
(SPOD (v.1.7, 1.8) September 20 2016)

Push e-mails notification should be added

**Comment by andrpet** [comment]
More details are needed for this issue. 
Eg.
 * For witch features (agora, cocreation, what's news)
 * Frequency
 * Modularity
 * Configurability

**Comment by vitsca** [comment]
Also, another important issue here, as pointed by Luca, is the mail server.. we cannot (can we) host a SMTP mailer, .. nor we can devote to Google (who has limits on automatic emails).. providers that charge it are available, though.. (@LucaVicidomini)

**Comment by vitsca** [comment]
Moved to the project Architecture.. @lucavicidomini  can provide more details (here) on the providers for email? thanks

**Comment by lucavicidomini** [comment]
Yes, we are currently using GMail via SMTP protocol. GMail states that the limit is 2000 email sent per day: it may seem a lot, but I actually hit that limit a lot of times before on another project. I suspect that GMail suspends an SMTP account if it tries to send few mails simultaneously, and it's a very likely occurrence since sending a mail through SMTP (at least with Google) takes several seconds to complete.

Here there are few services that can be evaluated: https://sendgrid.com, http://mailgun.com/, http://mailjet.com/, https://aws.amazon.com/ses/, https://elasticemail.com/... actually this list can grow indefinitely, one can just Google [email api](https://www.google.it/search?q=email+api).

**Comment by vitsca** [comment]
Amazon offers 0.10 us $ x 1000 messages. Assume 10000 msgs x day (wow). 30$
x month is acceptable. We must only find how to pay Amazon 😀

Il 15 Ott 2016 09:17, "Luca Vicidomini" <notifications@github.com> ha
scritto:

**Comment by lucavicidomini** [comment]
Merged with #89
