### ISSUE TITLE
[Wishlist][Enhancement] Logo

### ISSUE THREAD

**Issue by serahrono** [routetopa/spod#74]
It would be great if SPOD got its own logo in the coming months.

**Comment by vitsca** [comment]
This is what we had in the project proposal.. not the best one, I agree.. ![logo-pa-spod](https://cloud.githubusercontent.com/assets/2544302/19360300/3ab852e0-917e-11e6-8505-13096630ec61.png)

**Comment by callmealien** [comment]
Thanks for sharing this, @vitsca. First impression, it draws from ROUTETOPA's original logo, so the consistency isn't all that bad. I will float it to a design audience and share feedback here. Thank you.

**Comment by callmealien** [comment]
Good morning @vitsca. Feedback from some of the people I've been able to talk to about this project: 
The acronyms in the logo are confusing to new users, it would take a bit of cramming / repetitive reading to remember the acronyms and what they stand for as an outsider/ target user. 
Since this logo borrows from the ROUTETOPA logo, is there scope for rebranding, so that we can, for example, invite suggestions from our designer community for logos that would work better, being both memorable and descriptive?

**Comment by vitsca** [comment]
I agree with the comments.. the logo I showed you was "designed" in brief time for assembling the proposal.. so not very well thought of. I would say that suggestions are welcomed: I would favor an open approach to that, with the ROUTE-TO-PA team casting their vote, for both a SPOD and a TET logo .. I would suggest to keep, if possible, some connection to the ROUTE-TO-PA logo which in my opinion is memorable.. but, hey, I am one vote.. so, please proceed and thanks!
